version: "3"

tasks:
  build:
    cmds:
      - go build -o bin/app ./cmd/api
  run:
    cmds:
      - go run ./cmd/api
  lint:
    cmds:
      - golangci-lint run ./...
  migrate-up:
    cmds:
      - migrate -path db/migrations -database "url" up
  migrate-down:
    cmds:
      - migrate -path db/migrations -database "url" down
  docker-up:
    cmds:
      - docker compose -f docker/docker-compose.yml up -d 
  docker-down:
    cmds:
      - docker compose -f docker/docker-compose.yml down
  format:
    cmds:
      - go fmt ./...

      
