version: "3"

tasks:
  build:
    cmds:
      - go build -o bin/app ./cmd/api
  run:
    cmds:
      - go run ./cmd/api
  lint:
    cmds:
      - golangci-lint run ./...
  migrate-up:
    cmds:
      - migrate -path db/migrations -database "postgresql://neondb_owner:npg_y9ph0jPlEYAe@ep-nameless-paper-a4eyqgdh-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require" up
  migrate-down:
    cmds:
      - migrate -path db/migrations -database "postgresql://neondb_owner:npg_y9ph0jPlEYAe@ep-nameless-paper-a4eyqgdh-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require" down
  docker-up:
    cmds:
      - docker compose -f docker/docker-compose.yml up -d 
  docker-down:
    cmds:
      - docker compose -f docker/docker-compose.yml down
  format:
    cmds:
      - go fmt ./...

      